# Generated by Django 5.1.3 on 2024-11-20 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_raiting_profile_rating_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.contesttype'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='compilers',
            field=models.ManyToManyField(through='main.CompilerOnContest', to='main.compiler'),
        ),
    ]
