# Generated by Django 5.1.3 on 2024-11-24 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_answer_created_at_answer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
