# Generated by Django 5.1.3 on 2024-11-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_answer_user_test_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='statement',
            field=models.TextField(),
        ),
    ]
