# Generated by Django 5.1.3 on 2024-11-27 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_task_input_alter_task_note_alter_task_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercode',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='main.task'),
        ),
    ]
