# Generated by Django 5.1.3 on 2024-12-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_answercode_code_alter_answeroption_task'),
        ('main', '0007_alter_answeroption_task_checker_task_checker'),
    ]

    operations = [
    ]
