# Generated by Django 5.1.3 on 2024-12-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20241201_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='memory_limit',
            field=models.IntegerField(blank=True, default=64, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_limit',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
