# Generated by Django 5.1.3 on 2024-12-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_task_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='penalty',
        ),
    ]
