# Generated by Django 5.1.3 on 2024-12-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_answer_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='contest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.contest'),
            preserve_default=False,
        ),
    ]
