services:
  web:
    build: web/
    ports:
      - "8000:8000"
    volumes:
      - ./web/:/app/
  postgres:
    image: postgres
    ports:
      - "6401:5432"
    env_file: .postgres.env
    volumes:
      - pg-data:/data/postgres
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    user: "${UID}:${GID}"
    # restart: always
    ports:
      - 15672:15672
      - 5672:5672
    env_file: .rabbit.env
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rmq:/var/lib/rabbitmq
  runner:
    image: ts-runner
    environment:
      - RUNEXE=/runexe/build/runexe
    env_file: .runner.env
volumes:
  pg-data:
