services:
  web:
    build: web/
    ports:
      - "8000:8000"
  postgres:
    image: postgres
    ports:
      - "6401:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/data/postgres"
    volumes:
      - pg-data:/data/postgres

volumes:
  pg-data: