name: Codecov

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  TESTLIB: testlib/testlib.h
  SQLITE_MODE: True
  RMQ_DEBUG: True

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r source/web/requirements.txt
    - name: Clone Testlib
      run: |
        mkdir testlib/
        cd testlib
        wget https://raw.githubusercontent.com/MikeMirzayanov/testlib/refs/heads/master/testlib.h
    - name: Prepare database
      run: |
        export RUNEXE=source/
        python source/web/manage.py migrate
    - name: Run Tests
      run: |
        export RUNEXE=source/
        pytest source/web/
    - name: Generate coverage
      run: |
        export RUNEXE=source/
        coverage run -m pytest source/web/
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}